### PR TITLE
Added app icons and .DS_store to git ignore for future mac contributors

### PR DESCRIPTION
**Pull request by Wmitrut**
- Added app icons on img directory in some extension formats (svg included if the generated icon will sometime be needed)

- .DS_store to git ignore for future mac contributors because that was missing

### CODE REVIEW

**Comment by Wmitrut** [comment]
Yeah!, I`ll do that!

**Comment by Wmitrut** [comment]
Done

**Comment by anapaulagomes** [comment]
My fault: one more thing is missing and it will break stuff if we merge it: [`const tray = new Tray(`${__dirname}/app/img/temp.png`);`](https://github.com/anapaulagomes/pardal/blob/5ae542b0326a482e2eed19472bc3236a338b985f/index.js#L22). We just need to replace by `icon.png`. 🙏 @Wmitrut 

I must say: the new icon is dope!

screen shot 2019-03-04 at 18 19 30

**Comment by Wmitrut** [comment]
Easy peasy lemon squeezy - it`s done

**Pull request merged**
